### PR TITLE
Added dates 

### PR DESCRIPTION
**Pull request by neethanm**
image

### CODE REVIEW

**Comment by neethanm** [comment]
added dates to awards page (issue #9)

**Comment by anuragrao04** [comment]
Please use CSS to style it. Make it look like eye candy and more in line with the styling of the rest of the application.

**Comment by anuragrao04** [comment]
You are free to use tailwind-css

**Comment by neethanm** [comment]
yes, working on that

**Comment by anuragrao04** [comment]
okayy

**Comment by neethanm** [comment]
i have further modified the css of the dates and added a calendar icon as well

**Comment by anuragrao04** [comment]
that looks great, please just center the text in the card and you should be done with this PR!

**Comment by neethanm** [comment]
Centered text in the names column.

**Comment by anuragrao04** [comment]
lgtm!

**Comment by anuragrao04** [comment]
!bounty 50

**Pull request closed without merging**
