### PR TITLE
Issue 3 pull request

### PR DESCRIPTION
**Pull request by akshatnavlani**

### CODE REVIEW

**Comment by anuragrao04** [comment]
reviewing

**Comment by anuragrao04** [comment]
I don't see any changes in your PR. You've just added a bunch of new lines everywhere. Please talk to me in real life to explain about any changes you made which I might have missed. Until then, I will not consider this valid.

**Comment by anuragrao04** [comment]
Hello, sorry for the previous comment. I have seen the changes. There is one little problem. Longer names are not rendered properly and tend to nearly overflow the card. Please fix that and I'll merge your PR!


Here are a few screenshots:

Screenshot 2023-10-13 at 10 15 46 PM
Screenshot 2023-10-13 at 10 15 41 PM

**Comment by akshatnavlani** [comment]
Please check now.

**Comment by anuragrao04** [comment]
this looks good to me!

**Comment by anuragrao04** [comment]
!bounty 30

**Comment by anuragrao04** [comment]
25 + 5 points for good communication

**Pull request closed without merging**
